<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
    <TargetPlatformMinVersion>10.0.19041.0</TargetPlatformMinVersion>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <Platforms>x64</Platforms>
    <UseWinUI>true</UseWinUI>
    <EnableMsixTooling>false</EnableMsixTooling>
    <WindowsPackageType>None</WindowsPackageType>
    <WindowsAppSDKSelfContained>true</WindowsAppSDKSelfContained>
    <DefineConstants>DISABLE_XAML_GENERATED_MAIN</DefineConstants>
    <EnableDefaultApplicationDefinition>false</EnableDefaultApplicationDefinition>
    <EnableDefaultPageItems>false</EnableDefaultPageItems>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.WindowsAppSDK" />
  </ItemGroup>
  <ItemGroup>
    <ApplicationDefinition Include="App.xaml" />
    <Page Include="History\HistoryWindow.xaml" />
    <Page Include="Popup\TranslationWindow.xaml" />
    <Page Include="Settings\SettingsWindow.xaml" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\NTranslate.Platform\NTranslate.Platform.csproj" />
    <ProjectReference Include="..\NTranslate.Core\NTranslate.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="NTranslate.App.Tests" />
  </ItemGroup>
</Project>
